spring:
  datasource:
    driverClassName:
    url: jdbc:mysql://localhost:3306/quartz_demo
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: hailylydk@gmail.com
    password: Lycth@24092001
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate




